---
- hosts: zabbixServer
  remote_user: root
  vars_files:
    - server_vars.yml
  tasks:
    - name: "modify Apache && set firewalld && modify selinux config"
      include: 
        - service.yml

    - name: "install zabbix-server && modify config"
      include: 
        - zabbix_server.yml

    - name: "install & modify mysql"
      include: 
        - mysql.yml
  handlers:
    - handlers.yml

